services:
  stat-server:
    build:
      context: .
      dockerfile: stat/stat-server/Dockerfile
    container_name: stat-server
    restart: unless-stopped
    ports:
      - "9090:9090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://stat-db:5432/stats
      SPRING_DATASOURCE_USERNAME: stats_user
      SPRING_DATASOURCE_PASSWORD: secret
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:9090/actuator/health || exit 1
      interval: 30s
      timeout: 5s
      start_period: 30s
      retries: 5
    depends_on:
      stat-db:
        condition: service_healthy

  stat-db:
    image: postgres:17.7-alpine3.23
    container_name: stat-db
    restart: unless-stopped
    ports:
      - "13000:5432"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=stats_user
      - POSTGRES_PASSWORD=secret
    volumes:
      - stats-db-data:/var/lib/postgresql/data/
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  ewm-service:
    build:
      context: .
      dockerfile: main-service/Dockerfile
    container_name: ewm-service
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://ewm-db:5432/ewm
      SPRING_DATASOURCE_USERNAME: ewm_user
      SPRING_DATASOURCE_PASSWORD: secret
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8080/actuator/health || exit 1
      interval: 30s
      timeout: 5s
      start_period: 30s
      retries: 5
    depends_on:
      ewm-db:
        condition: service_healthy

  ewm-db:
    image: postgres:17.7-alpine3.23
    container_name: postgres-db
    restart: unless-stopped
    ports:
      - "13001:5432"
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=ewm_user
      - POSTGRES_PASSWORD=secret
    volumes:
      - ewm-db-data:/var/lib/postgresql/data/
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

volumes:
  stats-db-data:
  ewm-db-data:
